accounts/urls.py
from knox import views as knox_views
from .views import LoginAPI
from django.urls import path

urlpatterns = [
    path('api/login/', LoginAPI.as_view(), name='login'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from website import views
from django.views.i18n import JavaScriptCatalog
from django.urls import path,include


urlpatterns = [
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('admin/', admin.site.urls),
    path('', include(('user.urls'))),
    path('home/', include('website.urls')),

    
]

user/urls.py
from django.urls import path

from . import views

app_name="user"

urlpatterns = [
	path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    
]

website/urls.py
from django.urls import path
from . import views


app_name = "website" 
urlpatterns = [
    path('', views.index ),
    path('login/', views.login ),
    path('todolist/', views.todolist),
    
]

accounts/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models


class Student(models.Model):
	Student_pk = models.BigAutoField(auto_created=True, primary_key=True)
	Student_id = models.CharField(max_length=20 ,null=True)
	Student_prefix = models.CharField(max_length=5 ,null=True)
	Student_name_th = models.CharField(max_length=200 ,null=True)
	Student_name_en = models.CharField(max_length=200 ,null=True)
	Student_email = models.CharField(max_length=200 ,null=True)
	Student_faculty = models.CharField(max_length=200 ,null=True)
	Student_department = models.CharField(max_length=200 ,null=True)
	Student_step = models.IntegerField(default = 0 ,null=True)
# Create your models here.

website/models.py
from django.db import models

# Create your models here.


class ListModel(models.Model):
    date = models.DateField(null=True)
    list = models.CharField(max_length=64, null=True)

user/forms.py
# from django import forms  
# from django.contrib.auth.forms import UserCreationForm  
# from django.contrib.auth.models import User  
  
# class SignupForm(UserCreationForm):  
#     email = forms.EmailField(max_length=200, help_text='Required')  
#     class Meta:  
#         model = User  
#         fields = ('username', 'email', 'password1', 'password2')  

website/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.admin.widgets import  AdminDateWidget, AdminTimeWidget, AdminSplitDateTime
from .models import *


class todoForm(forms.Form):
    date = forms.DateField(widget=AdminDateWidget())
    list = forms.CharField(max_length=160)

class ListModelForm(forms.ModelForm):
    class Meta:
        model = ListModel
        fields = "__all__"
        widgets = {
            "date": AdminDateWidget(),
        }

accounts/views.py
from django.contrib.auth import login

from rest_framework import permissions
from rest_framework.authtoken.serializers import AuthTokenSerializer
from knox.views import LoginView as KnoxLoginView

class LoginAPI(KnoxLoginView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        serializer = AuthTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super(LoginAPI, self).post(request, format=None)

user/views.py
import email
from unicodedata import name
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
import requests
import pandas as pd
import json

from .models import Student
# Create your views here.


def index(request):
    if request.user.is_authenticated:
        return render(request, 'user/home.html')
    return redirect("/login")


def login_view(request):
    if request.user.is_authenticated:
        return render(request, 'user/home.html')
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None and user.is_superuser:
            login(request, user)
            return redirect("/admin")

        else:

            login_status = login_api(username, password)

            if login_status == 200:
                user = authenticate(
                    request, username=username, password=password)

                if not request.user.is_authenticated:
                    header = {
                        'Content-Type': 'application/json',
                        'Application-Key': 'TU240a80e5357e5d9279be402378381dfdfe126518202b4a6f5b30a4fb6218476b5ed6436d7a53ba7cc8009994e1ced28e'
                    }
                    pull_api = requests.get(
                        'https://restapi.tu.ac.th/api/v2/profile/std/info/?id='+str(username), headers=header)
                    data_student = json.loads(pull_api.content).get("data")
                    first_name, surname = (
                        data_student["displayname_th"]).split(" ")
                    email = data_student["email"]
                    # print(User.objects.all().username)
                    all_users = User.objects.values_list('username', flat=True)
                    print(username in list(all_users))
                    # print(all_users[]['username'])
                    if username not in list(all_users):
                        user = User.objects.create_user(username=username,
                                                        password=password,
                                                        first_name=first_name,
                                                        last_name=surname,
                                                        email=email)
                    user.save()

                if user is not None:
                    login(request, user)
                    return redirect("/")

            else:
                messages.info(request, "invalid Student ID or password")
    return render(request, 'user/login.html')


def logout_view(request):
    logout(request)
    messages.success(request, "Logged out.")
    return render(request, "user/login.html", {
        "messages": messages.get_messages(request)
    })


# login with tu api
def login_api(username, password):
    header = {
        'Content-Type': 'application/json',
        'Application-Key': 'TU240a80e5357e5d9279be402378381dfdfe126518202b4a6f5b30a4fb6218476b5ed6436d7a53ba7cc8009994e1ced28e'
    }

    body = {"UserName": username, "PassWord": password}

    res = requests.post(
        "https://restapi.tu.ac.th/api/v1/auth/Ad/verify", headers=header, json=body)

    return res.status_code

website/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from datetime import date, datetime
from django.contrib import messages

def index(request):
     
    return render(request, 'index.html')

def login(request):
    return render(request, 'login.html')


def todolist(request):
    if request.method == "POST":
        form = ListModelForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print("Error", form.errors)
    form = ListModelForm()
    show = ListModel.objects.all()
    return render(request, 'todolist.html', {'form':form , 'show':show } )



# def todolist(request):
#     form = todoForm()
#     date_now = datetime.now()
#     if request.method == 'POST':
#         todo_input = request.POST.get("todo")
#         date_input = request.POST.get("date_input")
#         if datetime(int(date_input[:4]), int(date_input[5:7]), int(date_input[8:]),) <= date_now:
#             messages.add_message(request, messages.SUCCESS, f"ไม่สามารถเพิ่มรายการได้ กรุณาเลือกวันให้ถูกต้อง")   #กรณีเลือกวันที่ผ่านมาแล้ว
#             return redirect("doctors:appointment", pk)
#         appointment = Appointment.objects.create(
#             Doctor_id=doctor,
#             todo=todo_input
#         )
#         appointment.dateapp = date_input
#         appointment.save()
#         return redirect("doctors:profile")

#     context = {"form": form, "doctor": doctor}
#     return render(request, "doctors/appointment_patient.html", context)

templates/todolist.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% url 'js-catlog' %}"></script>
    <script src="{% static '/admin/js/core.js' %}"></script>
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">
    <title>Follow @kira.boi</title>
</head>

<body>
    <form method="POST" class="text-center">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" name="Submit" id="submit">
    </form>

</body>

</html>

user/templates/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  
{% endautoescape %}  

user/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  
    
</head>

<body>
    <main>
        <section class="header">
            <nav>
              <div class="nav-links" id="navLinks">
                <ul>
                  <li><a href="{% url 'main:index' %}">Home</a></li>
                  <li><a href="{% url 'main:news' %}">Internship</a></li>
                  <li><a href="#" class="About">About</a>
                <div class="sub-about">
                  <ul>
                    <a href="https://github.com/cn332proj/cn332proj"><li>GitHub</li></a>
                    <a href="https://www.youtube.com/watch?v=O9XSYX4t2m8"><li>Youtube</li></a>
                  </ul>
                </div>
              </li>
              <li><a href="{% url 'user:logout' %}">Log out</a></li>
              </ul>
              </div>
            </nav>
          </section>
    <nav>
        <section class="header">
        <div class="menu-bar ">
            <img src="{% static 'images/Logo_ECE.png' %}" height="50px" style="margin: 6px" />
            <a href="">เข้าสู่ระบบ</a>
            <a href="">เอกสารวิชาโครงงาน</a>
        </div>   
        </section>
    </nav>
     <section class="body">
        {% block content %}
        {% endblock %}
    </section>
    </main>
</body>
</html>

user/templates/base_user.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>login</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  
    
</head>

<!-- <body>
    <main> -->
    <!-- <nav>
        <section class="header">
        <div class="menu-bar ">
            <img src="{% static 'images/Logo_ECE.png' %}" height="50px" style="margin: 6px" />
            <a href="">เข้าสู่ระบบ</a>
            <a href="">เอกสารวิชาโครงงาน</a>
        </div>   
        </section>
    </nav> -->
    <!-- <section class="body">
        <center><img src="{% static 'images/TSE-logo.png' %}" height="100px" style="margin: 6px"/></center>
        
    </section> -->
    <!-- </main>
</body> -->
{% block body %}
        {% endblock %}
</html>

user/templates/user/home.html
{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}! <br>
  {{ user.first_name }} 
  {{ user.last_name }}<br>
  {{ user.email }}<br>

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}
<a href="{% url 'user:logout' %}">Log out</a>

user/templates/user/index.html
{% block body %}  

<a href="{% url 'user:logout' %}">Log out</a>

{% endblock %}

user/templates/user/login.html
{% extends 'base_user.html' %}
{% load static %}
{% block body %}  
<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
  <div class="card card0 border-0">
      <div class="row d-flex">
          <div class="col-lg-6">
              <div class="card1 pb-5">
                  <div class="row">
                      <img src="{% static 'images/TSE-logo.png' %}" class="logo">
                  </div>
                  <div class="row px-3 justify-content-center mt-4 mb-5 border-line">
                      <img src="https://i.imgur.com/uNGdWHi.png" class="image">
                  </div>
              </div>
          </div>
          <div class="col-lg-6">
              <div class="card2 card border-0 px-4 py-5">
                  <div class="row px-3 mb-4">
                      <div class="line"></div>
                      <bigger class="or text-center">LOGIN</bigger>
                      <div class="line"></div>
                  </div>
                  <form method="post" action="{% url 'user:login' %}" id="login-form" class="login-form" autocomplete="off" role="main">
                    {% csrf_token %}
                  <div class="row px-3">
                      <label class="mb-1"><h6 class="mb-0 text-sm"><span class="required">Username</span></h6></label>
                      <input class="mb-4" type="text" name="username" placeholder="Enter Username">
                  </div>
                  <div class="row px-3">
                      <label class="mb-1"><h6 class="mb-0 text-sm">Password</h6></label>
                      <input type="password" name="password" placeholder="Enter password">
                  </div>
                  <div class="row px-3 mb-4">
                      <div class="custom-control custom-checkbox custom-control-inline">
                          <input id="chk1" type="checkbox" name="chk" class="custom-control-input"> 
                          <label for="chk1" class="custom-control-label text-sm">Remember me</label>
                      </div>
                      <a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
                  </div>
                  <div class="row mb-3 px-3">
                      <button type="submit" class="btn btn-blue text-center">Login</button>
                  </div>
                  {% if messages %}
                      {% for message in messages %}
                        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                      {% endfor %}
                  {% endif %}
                  </form>
                  <div class="row mb-4 px-3">
                      <small class="font-weight-bold">Don't have an account? <a class="text-danger ">Register</a></small>
                  </div>
              </div>
          </div>
      </div>
      <div class="bg-blue py-4">
          <div class="row px-3">
              <small class="ml-4 ml-sm-5 mb-2"></small>
              <div class="social-contact ml-4 ml-sm-auto">
                  <span class="fa fa-facebook mr-4 text-sm"></span>
                  <span class="fa fa-google-plus mr-4 text-sm"></span>
                  <span class="fa fa-linkedin mr-4 text-sm"></span>
                  <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

user/templates/user/signup.html
{% block content %}  
<div class = "container">  
  <h2>Sign up</h2>  
  <form method="post">  
    {% csrf_token %}  
      {% for field in form %}  
      <p>  
        {{ field.label_tag }}<br>  
        {{ field }}  
        {% if field.help_text %}  
          <small style="display: none ">{{ field.help_text }}</small>  
        {% endif %}  
        {% for error in field.errors %}  
          <p style="color: red">{{ error }}</p>  
        {% endfor %}  
      </p>  
      {% endfor %}  
    <button type="submit">Sign up</button>  
  </form>  
</div>  
{% endblock %}  

website/templates/index.html
{% include "layout.html" %}
<!DOCTYPE html>
    <html>


    {% block head %}
        <h1>index</h1>
    <head>
        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            td,
            th {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
            }
        </style>
    </head>
    {% endblock %}
    {% block content %}
    <body>

        <h2>HTML Table</h2>

    </body>
    {% endblock %}
</html>

website/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>bar</title>
    </head>
        <!-- {% if request.user.is_active %} -->
        <!-- <div >
            <a href="{% url 'doctors:profile' %}" >
                <img src =" {{request.user.patient.profile_pic.url}}" >
                <p>{{request.user.patient.First_name}}</p> 
            </a>
        </div> -->
        <!-- {% else %} -->
        <div>
            <a href="login" class="signin">LOG IN</a>
        </div>
        <!-- {% endif %} -->

   <div>
        <a href="todolist">สิ่งที่ต้องทำ</a>
        <a href="">ประกาศข่าวสาร</a>
        <a href="">แผนการดำเนินงาน</a>
        <a href="">อัพโหลดเอกสาร</a>
        <a href="">โครงงานนักศึกษา</a>
        <a href="">คะแนนโครงงาน</a>
        <a href="">เกณฑ์การตัดเกรด</a>
        <a href="">จัดการข้อมูลพื้นฐาน</a>
        <a href="">จัดการปีการศึกษา</a>
        <a href="">ตั้งค่า</a>

        <!-- {% if request.user.is_superuser %} -->
        <!-- {% else %} -->

        <!-- {% endif %} -->
    </div>

    <div>
        <a href = "" >
            <div>
                <p>ออกจากระบบ</p>
            </div>
        </a>
    </div>

    </body>

</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>login</h1>
</body>

</html>

website/templates/todolist.html
{% include "layout.html" %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% url 'js-catlog' %}"></script>
    <script src="{% static '/admin/js/core.js' %}"></script>
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">
    <title>Follow @kira.boi</title>
</head>

<body>
    <form method="POST" class="text-center">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" name="Submit" id="submit">
    </form>

    <table>
        {% for show in show %}
        <tr>
            <td>
                {{show.date}}
                {{show.list}}
            </td>
        </tr>
        {% endfor %}

</body>

</html>